// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dm/action.proto

package com.triclass.dm;

public final class ActionOuterClass {
  private ActionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_triclass_dm_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_triclass_dm_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017dm/action.proto\022\013triclass.dm\032\022dm/heart" +
      "beat.proto\032\027dm/change_account.proto\"t\n\006A" +
      "ction\022+\n\theartbeat\030\001 \001(\0132\026.triclass.dm.H" +
      "eartbeatH\000\0223\n\rchangeAccount\030\002 \001(\0132\032.tric" +
      "lass.dm.ChangeAccountH\000B\010\n\006actionB\034\n\017com" +
      ".triclass.dmP\001Z\007./dm;dmb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.triclass.dm.HeartbeatOuterClass.getDescriptor(),
          com.triclass.dm.ChangeAccountOuterClass.getDescriptor(),
        });
    internal_static_triclass_dm_Action_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_triclass_dm_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_triclass_dm_Action_descriptor,
        new java.lang.String[] { "Heartbeat", "ChangeAccount", "Action", });
    com.triclass.dm.HeartbeatOuterClass.getDescriptor();
    com.triclass.dm.ChangeAccountOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
