// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dm/action.proto

package com.triclass.dm;

/**
 * <pre>
 * 数据上报
 * </pre>
 *
 * Protobuf type {@code triclass.dm.Action}
 */
public final class Action extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:triclass.dm.Action)
    ActionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Action.newBuilder() to construct.
  private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Action() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Action();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Action(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.triclass.dm.Heartbeat.Builder subBuilder = null;
            if (actionCase_ == 1) {
              subBuilder = ((com.triclass.dm.Heartbeat) action_).toBuilder();
            }
            action_ =
                input.readMessage(com.triclass.dm.Heartbeat.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.triclass.dm.Heartbeat) action_);
              action_ = subBuilder.buildPartial();
            }
            actionCase_ = 1;
            break;
          }
          case 18: {
            com.triclass.dm.ChangeAccount.Builder subBuilder = null;
            if (actionCase_ == 2) {
              subBuilder = ((com.triclass.dm.ChangeAccount) action_).toBuilder();
            }
            action_ =
                input.readMessage(com.triclass.dm.ChangeAccount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.triclass.dm.ChangeAccount) action_);
              action_ = subBuilder.buildPartial();
            }
            actionCase_ = 2;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.triclass.dm.ActionOuterClass.internal_static_triclass_dm_Action_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.triclass.dm.ActionOuterClass.internal_static_triclass_dm_Action_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.triclass.dm.Action.class, com.triclass.dm.Action.Builder.class);
  }

  private int actionCase_ = 0;
  private java.lang.Object action_;
  public enum ActionCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    HEARTBEAT(1),
    CHANGEACCOUNT(2),
    ACTION_NOT_SET(0);
    private final int value;
    private ActionCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionCase valueOf(int value) {
      return forNumber(value);
    }

    public static ActionCase forNumber(int value) {
      switch (value) {
        case 1: return HEARTBEAT;
        case 2: return CHANGEACCOUNT;
        case 0: return ACTION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ActionCase
  getActionCase() {
    return ActionCase.forNumber(
        actionCase_);
  }

  public static final int HEARTBEAT_FIELD_NUMBER = 1;
  /**
   * <pre>
   * 心跳消息
   * </pre>
   *
   * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
   * @return Whether the heartbeat field is set.
   */
  @java.lang.Override
  public boolean hasHeartbeat() {
    return actionCase_ == 1;
  }
  /**
   * <pre>
   * 心跳消息
   * </pre>
   *
   * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
   * @return The heartbeat.
   */
  @java.lang.Override
  public com.triclass.dm.Heartbeat getHeartbeat() {
    if (actionCase_ == 1) {
       return (com.triclass.dm.Heartbeat) action_;
    }
    return com.triclass.dm.Heartbeat.getDefaultInstance();
  }
  /**
   * <pre>
   * 心跳消息
   * </pre>
   *
   * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
   */
  @java.lang.Override
  public com.triclass.dm.HeartbeatOrBuilder getHeartbeatOrBuilder() {
    if (actionCase_ == 1) {
       return (com.triclass.dm.Heartbeat) action_;
    }
    return com.triclass.dm.Heartbeat.getDefaultInstance();
  }

  public static final int CHANGEACCOUNT_FIELD_NUMBER = 2;
  /**
   * <pre>
   * 修改云视讯账号
   * </pre>
   *
   * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
   * @return Whether the changeAccount field is set.
   */
  @java.lang.Override
  public boolean hasChangeAccount() {
    return actionCase_ == 2;
  }
  /**
   * <pre>
   * 修改云视讯账号
   * </pre>
   *
   * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
   * @return The changeAccount.
   */
  @java.lang.Override
  public com.triclass.dm.ChangeAccount getChangeAccount() {
    if (actionCase_ == 2) {
       return (com.triclass.dm.ChangeAccount) action_;
    }
    return com.triclass.dm.ChangeAccount.getDefaultInstance();
  }
  /**
   * <pre>
   * 修改云视讯账号
   * </pre>
   *
   * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
   */
  @java.lang.Override
  public com.triclass.dm.ChangeAccountOrBuilder getChangeAccountOrBuilder() {
    if (actionCase_ == 2) {
       return (com.triclass.dm.ChangeAccount) action_;
    }
    return com.triclass.dm.ChangeAccount.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (actionCase_ == 1) {
      output.writeMessage(1, (com.triclass.dm.Heartbeat) action_);
    }
    if (actionCase_ == 2) {
      output.writeMessage(2, (com.triclass.dm.ChangeAccount) action_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (actionCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.triclass.dm.Heartbeat) action_);
    }
    if (actionCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.triclass.dm.ChangeAccount) action_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.triclass.dm.Action)) {
      return super.equals(obj);
    }
    com.triclass.dm.Action other = (com.triclass.dm.Action) obj;

    if (!getActionCase().equals(other.getActionCase())) return false;
    switch (actionCase_) {
      case 1:
        if (!getHeartbeat()
            .equals(other.getHeartbeat())) return false;
        break;
      case 2:
        if (!getChangeAccount()
            .equals(other.getChangeAccount())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (actionCase_) {
      case 1:
        hash = (37 * hash) + HEARTBEAT_FIELD_NUMBER;
        hash = (53 * hash) + getHeartbeat().hashCode();
        break;
      case 2:
        hash = (37 * hash) + CHANGEACCOUNT_FIELD_NUMBER;
        hash = (53 * hash) + getChangeAccount().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.triclass.dm.Action parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.dm.Action parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.dm.Action parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.dm.Action parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.dm.Action parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.dm.Action parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.dm.Action parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.triclass.dm.Action parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.triclass.dm.Action parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.triclass.dm.Action parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.triclass.dm.Action parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.triclass.dm.Action parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.triclass.dm.Action prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 数据上报
   * </pre>
   *
   * Protobuf type {@code triclass.dm.Action}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:triclass.dm.Action)
      com.triclass.dm.ActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.triclass.dm.ActionOuterClass.internal_static_triclass_dm_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.triclass.dm.ActionOuterClass.internal_static_triclass_dm_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.triclass.dm.Action.class, com.triclass.dm.Action.Builder.class);
    }

    // Construct using com.triclass.dm.Action.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      actionCase_ = 0;
      action_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.triclass.dm.ActionOuterClass.internal_static_triclass_dm_Action_descriptor;
    }

    @java.lang.Override
    public com.triclass.dm.Action getDefaultInstanceForType() {
      return com.triclass.dm.Action.getDefaultInstance();
    }

    @java.lang.Override
    public com.triclass.dm.Action build() {
      com.triclass.dm.Action result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.triclass.dm.Action buildPartial() {
      com.triclass.dm.Action result = new com.triclass.dm.Action(this);
      if (actionCase_ == 1) {
        if (heartbeatBuilder_ == null) {
          result.action_ = action_;
        } else {
          result.action_ = heartbeatBuilder_.build();
        }
      }
      if (actionCase_ == 2) {
        if (changeAccountBuilder_ == null) {
          result.action_ = action_;
        } else {
          result.action_ = changeAccountBuilder_.build();
        }
      }
      result.actionCase_ = actionCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.triclass.dm.Action) {
        return mergeFrom((com.triclass.dm.Action)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.triclass.dm.Action other) {
      if (other == com.triclass.dm.Action.getDefaultInstance()) return this;
      switch (other.getActionCase()) {
        case HEARTBEAT: {
          mergeHeartbeat(other.getHeartbeat());
          break;
        }
        case CHANGEACCOUNT: {
          mergeChangeAccount(other.getChangeAccount());
          break;
        }
        case ACTION_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.triclass.dm.Action parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.triclass.dm.Action) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int actionCase_ = 0;
    private java.lang.Object action_;
    public ActionCase
        getActionCase() {
      return ActionCase.forNumber(
          actionCase_);
    }

    public Builder clearAction() {
      actionCase_ = 0;
      action_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.triclass.dm.Heartbeat, com.triclass.dm.Heartbeat.Builder, com.triclass.dm.HeartbeatOrBuilder> heartbeatBuilder_;
    /**
     * <pre>
     * 心跳消息
     * </pre>
     *
     * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
     * @return Whether the heartbeat field is set.
     */
    @java.lang.Override
    public boolean hasHeartbeat() {
      return actionCase_ == 1;
    }
    /**
     * <pre>
     * 心跳消息
     * </pre>
     *
     * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
     * @return The heartbeat.
     */
    @java.lang.Override
    public com.triclass.dm.Heartbeat getHeartbeat() {
      if (heartbeatBuilder_ == null) {
        if (actionCase_ == 1) {
          return (com.triclass.dm.Heartbeat) action_;
        }
        return com.triclass.dm.Heartbeat.getDefaultInstance();
      } else {
        if (actionCase_ == 1) {
          return heartbeatBuilder_.getMessage();
        }
        return com.triclass.dm.Heartbeat.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 心跳消息
     * </pre>
     *
     * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
     */
    public Builder setHeartbeat(com.triclass.dm.Heartbeat value) {
      if (heartbeatBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        action_ = value;
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(value);
      }
      actionCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * 心跳消息
     * </pre>
     *
     * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
     */
    public Builder setHeartbeat(
        com.triclass.dm.Heartbeat.Builder builderForValue) {
      if (heartbeatBuilder_ == null) {
        action_ = builderForValue.build();
        onChanged();
      } else {
        heartbeatBuilder_.setMessage(builderForValue.build());
      }
      actionCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * 心跳消息
     * </pre>
     *
     * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
     */
    public Builder mergeHeartbeat(com.triclass.dm.Heartbeat value) {
      if (heartbeatBuilder_ == null) {
        if (actionCase_ == 1 &&
            action_ != com.triclass.dm.Heartbeat.getDefaultInstance()) {
          action_ = com.triclass.dm.Heartbeat.newBuilder((com.triclass.dm.Heartbeat) action_)
              .mergeFrom(value).buildPartial();
        } else {
          action_ = value;
        }
        onChanged();
      } else {
        if (actionCase_ == 1) {
          heartbeatBuilder_.mergeFrom(value);
        }
        heartbeatBuilder_.setMessage(value);
      }
      actionCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * 心跳消息
     * </pre>
     *
     * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
     */
    public Builder clearHeartbeat() {
      if (heartbeatBuilder_ == null) {
        if (actionCase_ == 1) {
          actionCase_ = 0;
          action_ = null;
          onChanged();
        }
      } else {
        if (actionCase_ == 1) {
          actionCase_ = 0;
          action_ = null;
        }
        heartbeatBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 心跳消息
     * </pre>
     *
     * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
     */
    public com.triclass.dm.Heartbeat.Builder getHeartbeatBuilder() {
      return getHeartbeatFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 心跳消息
     * </pre>
     *
     * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
     */
    @java.lang.Override
    public com.triclass.dm.HeartbeatOrBuilder getHeartbeatOrBuilder() {
      if ((actionCase_ == 1) && (heartbeatBuilder_ != null)) {
        return heartbeatBuilder_.getMessageOrBuilder();
      } else {
        if (actionCase_ == 1) {
          return (com.triclass.dm.Heartbeat) action_;
        }
        return com.triclass.dm.Heartbeat.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 心跳消息
     * </pre>
     *
     * <code>.triclass.dm.Heartbeat heartbeat = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.triclass.dm.Heartbeat, com.triclass.dm.Heartbeat.Builder, com.triclass.dm.HeartbeatOrBuilder> 
        getHeartbeatFieldBuilder() {
      if (heartbeatBuilder_ == null) {
        if (!(actionCase_ == 1)) {
          action_ = com.triclass.dm.Heartbeat.getDefaultInstance();
        }
        heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.triclass.dm.Heartbeat, com.triclass.dm.Heartbeat.Builder, com.triclass.dm.HeartbeatOrBuilder>(
                (com.triclass.dm.Heartbeat) action_,
                getParentForChildren(),
                isClean());
        action_ = null;
      }
      actionCase_ = 1;
      onChanged();;
      return heartbeatBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.triclass.dm.ChangeAccount, com.triclass.dm.ChangeAccount.Builder, com.triclass.dm.ChangeAccountOrBuilder> changeAccountBuilder_;
    /**
     * <pre>
     * 修改云视讯账号
     * </pre>
     *
     * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
     * @return Whether the changeAccount field is set.
     */
    @java.lang.Override
    public boolean hasChangeAccount() {
      return actionCase_ == 2;
    }
    /**
     * <pre>
     * 修改云视讯账号
     * </pre>
     *
     * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
     * @return The changeAccount.
     */
    @java.lang.Override
    public com.triclass.dm.ChangeAccount getChangeAccount() {
      if (changeAccountBuilder_ == null) {
        if (actionCase_ == 2) {
          return (com.triclass.dm.ChangeAccount) action_;
        }
        return com.triclass.dm.ChangeAccount.getDefaultInstance();
      } else {
        if (actionCase_ == 2) {
          return changeAccountBuilder_.getMessage();
        }
        return com.triclass.dm.ChangeAccount.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 修改云视讯账号
     * </pre>
     *
     * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
     */
    public Builder setChangeAccount(com.triclass.dm.ChangeAccount value) {
      if (changeAccountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        action_ = value;
        onChanged();
      } else {
        changeAccountBuilder_.setMessage(value);
      }
      actionCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 修改云视讯账号
     * </pre>
     *
     * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
     */
    public Builder setChangeAccount(
        com.triclass.dm.ChangeAccount.Builder builderForValue) {
      if (changeAccountBuilder_ == null) {
        action_ = builderForValue.build();
        onChanged();
      } else {
        changeAccountBuilder_.setMessage(builderForValue.build());
      }
      actionCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 修改云视讯账号
     * </pre>
     *
     * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
     */
    public Builder mergeChangeAccount(com.triclass.dm.ChangeAccount value) {
      if (changeAccountBuilder_ == null) {
        if (actionCase_ == 2 &&
            action_ != com.triclass.dm.ChangeAccount.getDefaultInstance()) {
          action_ = com.triclass.dm.ChangeAccount.newBuilder((com.triclass.dm.ChangeAccount) action_)
              .mergeFrom(value).buildPartial();
        } else {
          action_ = value;
        }
        onChanged();
      } else {
        if (actionCase_ == 2) {
          changeAccountBuilder_.mergeFrom(value);
        }
        changeAccountBuilder_.setMessage(value);
      }
      actionCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 修改云视讯账号
     * </pre>
     *
     * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
     */
    public Builder clearChangeAccount() {
      if (changeAccountBuilder_ == null) {
        if (actionCase_ == 2) {
          actionCase_ = 0;
          action_ = null;
          onChanged();
        }
      } else {
        if (actionCase_ == 2) {
          actionCase_ = 0;
          action_ = null;
        }
        changeAccountBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 修改云视讯账号
     * </pre>
     *
     * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
     */
    public com.triclass.dm.ChangeAccount.Builder getChangeAccountBuilder() {
      return getChangeAccountFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 修改云视讯账号
     * </pre>
     *
     * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
     */
    @java.lang.Override
    public com.triclass.dm.ChangeAccountOrBuilder getChangeAccountOrBuilder() {
      if ((actionCase_ == 2) && (changeAccountBuilder_ != null)) {
        return changeAccountBuilder_.getMessageOrBuilder();
      } else {
        if (actionCase_ == 2) {
          return (com.triclass.dm.ChangeAccount) action_;
        }
        return com.triclass.dm.ChangeAccount.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 修改云视讯账号
     * </pre>
     *
     * <code>.triclass.dm.ChangeAccount changeAccount = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.triclass.dm.ChangeAccount, com.triclass.dm.ChangeAccount.Builder, com.triclass.dm.ChangeAccountOrBuilder> 
        getChangeAccountFieldBuilder() {
      if (changeAccountBuilder_ == null) {
        if (!(actionCase_ == 2)) {
          action_ = com.triclass.dm.ChangeAccount.getDefaultInstance();
        }
        changeAccountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.triclass.dm.ChangeAccount, com.triclass.dm.ChangeAccount.Builder, com.triclass.dm.ChangeAccountOrBuilder>(
                (com.triclass.dm.ChangeAccount) action_,
                getParentForChildren(),
                isClean());
        action_ = null;
      }
      actionCase_ = 2;
      onChanged();;
      return changeAccountBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:triclass.dm.Action)
  }

  // @@protoc_insertion_point(class_scope:triclass.dm.Action)
  private static final com.triclass.dm.Action DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.triclass.dm.Action();
  }

  public static com.triclass.dm.Action getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Action>
      PARSER = new com.google.protobuf.AbstractParser<Action>() {
    @java.lang.Override
    public Action parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Action(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Action> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Action> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.triclass.dm.Action getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

