// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dm/change_account.proto

package com.triclass.dm;

public interface ChangeAccountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.dm.ChangeAccount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 厂商
   * </pre>
   *
   * <code>.triclass.manufacturer.Manufacturer manufacturer = 1;</code>
   * @return The enum numeric value on the wire for manufacturer.
   */
  int getManufacturerValue();
  /**
   * <pre>
   * 厂商
   * </pre>
   *
   * <code>.triclass.manufacturer.Manufacturer manufacturer = 1;</code>
   * @return The manufacturer.
   */
  com.triclass.Manufacturer getManufacturer();

  /**
   * <pre>
   * 设备序列号
   * </pre>
   *
   * <code>string sn = 2;</code>
   * @return The sn.
   */
  java.lang.String getSn();
  /**
   * <pre>
   * 设备序列号
   * </pre>
   *
   * <code>string sn = 2;</code>
   * @return The bytes for sn.
   */
  com.google.protobuf.ByteString
      getSnBytes();

  /**
   * <pre>
   * 云视讯账号
   * </pre>
   *
   * <code>string account = 3;</code>
   * @return The account.
   */
  java.lang.String getAccount();
  /**
   * <pre>
   * 云视讯账号
   * </pre>
   *
   * <code>string account = 3;</code>
   * @return The bytes for account.
   */
  com.google.protobuf.ByteString
      getAccountBytes();
}
