// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dm/change_account.proto

package com.triclass.dm;

public final class ChangeAccountOuterClass {
  private ChangeAccountOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_triclass_dm_ChangeAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_triclass_dm_ChangeAccount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027dm/change_account.proto\022\013triclass.dm\032\022" +
      "manufacturer.proto\"g\n\rChangeAccount\0229\n\014m" +
      "anufacturer\030\001 \001(\0162#.triclass.manufacture" +
      "r.Manufacturer\022\n\n\002sn\030\002 \001(\t\022\017\n\007account\030\003 " +
      "\001(\tB\034\n\017com.triclass.dmP\001Z\007./dm;dmb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.triclass.ManufacturerOuterClass.getDescriptor(),
        });
    internal_static_triclass_dm_ChangeAccount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_triclass_dm_ChangeAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_triclass_dm_ChangeAccount_descriptor,
        new java.lang.String[] { "Manufacturer", "Sn", "Account", });
    com.triclass.ManufacturerOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
