// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dm/heartbeat.proto

package com.triclass.dm;

public interface HeartbeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.dm.Heartbeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 学校编号
   * </pre>
   *
   * <code>int64 schoolId = 1;</code>
   * @return The schoolId.
   */
  long getSchoolId();

  /**
   * <pre>
   * 厂商
   * </pre>
   *
   * <code>.triclass.manufacturer.Manufacturer manufacturer = 2;</code>
   * @return The enum numeric value on the wire for manufacturer.
   */
  int getManufacturerValue();
  /**
   * <pre>
   * 厂商
   * </pre>
   *
   * <code>.triclass.manufacturer.Manufacturer manufacturer = 2;</code>
   * @return The manufacturer.
   */
  com.triclass.Manufacturer getManufacturer();

  /**
   * <pre>
   * 设备序列号
   * </pre>
   *
   * <code>string sn = 3;</code>
   * @return The sn.
   */
  java.lang.String getSn();
  /**
   * <pre>
   * 设备序列号
   * </pre>
   *
   * <code>string sn = 3;</code>
   * @return The bytes for sn.
   */
  com.google.protobuf.ByteString
      getSnBytes();

  /**
   * <pre>
   * 设备状态
   * </pre>
   *
   * <code>.triclass.system.status.SystemStatus status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * 设备状态
   * </pre>
   *
   * <code>.triclass.system.status.SystemStatus status = 4;</code>
   * @return The status.
   */
  com.triclass.SystemStatus getStatus();
}
