// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dm/heartbeat.proto

package com.triclass.dm;

/**
 * <pre>
 * 心跳
 * </pre>
 *
 * Protobuf type {@code triclass.dm.Heartbeat}
 */
public final class Heartbeat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:triclass.dm.Heartbeat)
    HeartbeatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Heartbeat.newBuilder() to construct.
  private Heartbeat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Heartbeat() {
    manufacturer_ = 0;
    sn_ = "";
    status_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Heartbeat();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Heartbeat(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            schoolId_ = input.readInt64();
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            manufacturer_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            sn_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.triclass.dm.HeartbeatOuterClass.internal_static_triclass_dm_Heartbeat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.triclass.dm.HeartbeatOuterClass.internal_static_triclass_dm_Heartbeat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.triclass.dm.Heartbeat.class, com.triclass.dm.Heartbeat.Builder.class);
  }

  public static final int SCHOOLID_FIELD_NUMBER = 1;
  private long schoolId_;
  /**
   * <pre>
   * 学校编号
   * </pre>
   *
   * <code>int64 schoolId = 1;</code>
   * @return The schoolId.
   */
  @java.lang.Override
  public long getSchoolId() {
    return schoolId_;
  }

  public static final int MANUFACTURER_FIELD_NUMBER = 2;
  private int manufacturer_;
  /**
   * <pre>
   * 厂商
   * </pre>
   *
   * <code>.triclass.manufacturer.Manufacturer manufacturer = 2;</code>
   * @return The enum numeric value on the wire for manufacturer.
   */
  @java.lang.Override public int getManufacturerValue() {
    return manufacturer_;
  }
  /**
   * <pre>
   * 厂商
   * </pre>
   *
   * <code>.triclass.manufacturer.Manufacturer manufacturer = 2;</code>
   * @return The manufacturer.
   */
  @java.lang.Override public com.triclass.Manufacturer getManufacturer() {
    @SuppressWarnings("deprecation")
    com.triclass.Manufacturer result = com.triclass.Manufacturer.valueOf(manufacturer_);
    return result == null ? com.triclass.Manufacturer.UNRECOGNIZED : result;
  }

  public static final int SN_FIELD_NUMBER = 3;
  private volatile java.lang.Object sn_;
  /**
   * <pre>
   * 设备序列号
   * </pre>
   *
   * <code>string sn = 3;</code>
   * @return The sn.
   */
  @java.lang.Override
  public java.lang.String getSn() {
    java.lang.Object ref = sn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sn_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备序列号
   * </pre>
   *
   * <code>string sn = 3;</code>
   * @return The bytes for sn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSnBytes() {
    java.lang.Object ref = sn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_;
  /**
   * <pre>
   * 设备状态
   * </pre>
   *
   * <code>.triclass.system.status.SystemStatus status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <pre>
   * 设备状态
   * </pre>
   *
   * <code>.triclass.system.status.SystemStatus status = 4;</code>
   * @return The status.
   */
  @java.lang.Override public com.triclass.SystemStatus getStatus() {
    @SuppressWarnings("deprecation")
    com.triclass.SystemStatus result = com.triclass.SystemStatus.valueOf(status_);
    return result == null ? com.triclass.SystemStatus.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (schoolId_ != 0L) {
      output.writeInt64(1, schoolId_);
    }
    if (manufacturer_ != com.triclass.Manufacturer.UNKNOWN.getNumber()) {
      output.writeEnum(2, manufacturer_);
    }
    if (!getSnBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, sn_);
    }
    if (status_ != com.triclass.SystemStatus.UNKNOWN.getNumber()) {
      output.writeEnum(4, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (schoolId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, schoolId_);
    }
    if (manufacturer_ != com.triclass.Manufacturer.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, manufacturer_);
    }
    if (!getSnBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, sn_);
    }
    if (status_ != com.triclass.SystemStatus.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.triclass.dm.Heartbeat)) {
      return super.equals(obj);
    }
    com.triclass.dm.Heartbeat other = (com.triclass.dm.Heartbeat) obj;

    if (getSchoolId()
        != other.getSchoolId()) return false;
    if (manufacturer_ != other.manufacturer_) return false;
    if (!getSn()
        .equals(other.getSn())) return false;
    if (status_ != other.status_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHOOLID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSchoolId());
    hash = (37 * hash) + MANUFACTURER_FIELD_NUMBER;
    hash = (53 * hash) + manufacturer_;
    hash = (37 * hash) + SN_FIELD_NUMBER;
    hash = (53 * hash) + getSn().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.triclass.dm.Heartbeat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.dm.Heartbeat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.dm.Heartbeat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.dm.Heartbeat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.dm.Heartbeat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.dm.Heartbeat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.dm.Heartbeat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.triclass.dm.Heartbeat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.triclass.dm.Heartbeat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.triclass.dm.Heartbeat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.triclass.dm.Heartbeat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.triclass.dm.Heartbeat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.triclass.dm.Heartbeat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 心跳
   * </pre>
   *
   * Protobuf type {@code triclass.dm.Heartbeat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:triclass.dm.Heartbeat)
      com.triclass.dm.HeartbeatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.triclass.dm.HeartbeatOuterClass.internal_static_triclass_dm_Heartbeat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.triclass.dm.HeartbeatOuterClass.internal_static_triclass_dm_Heartbeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.triclass.dm.Heartbeat.class, com.triclass.dm.Heartbeat.Builder.class);
    }

    // Construct using com.triclass.dm.Heartbeat.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      schoolId_ = 0L;

      manufacturer_ = 0;

      sn_ = "";

      status_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.triclass.dm.HeartbeatOuterClass.internal_static_triclass_dm_Heartbeat_descriptor;
    }

    @java.lang.Override
    public com.triclass.dm.Heartbeat getDefaultInstanceForType() {
      return com.triclass.dm.Heartbeat.getDefaultInstance();
    }

    @java.lang.Override
    public com.triclass.dm.Heartbeat build() {
      com.triclass.dm.Heartbeat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.triclass.dm.Heartbeat buildPartial() {
      com.triclass.dm.Heartbeat result = new com.triclass.dm.Heartbeat(this);
      result.schoolId_ = schoolId_;
      result.manufacturer_ = manufacturer_;
      result.sn_ = sn_;
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.triclass.dm.Heartbeat) {
        return mergeFrom((com.triclass.dm.Heartbeat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.triclass.dm.Heartbeat other) {
      if (other == com.triclass.dm.Heartbeat.getDefaultInstance()) return this;
      if (other.getSchoolId() != 0L) {
        setSchoolId(other.getSchoolId());
      }
      if (other.manufacturer_ != 0) {
        setManufacturerValue(other.getManufacturerValue());
      }
      if (!other.getSn().isEmpty()) {
        sn_ = other.sn_;
        onChanged();
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.triclass.dm.Heartbeat parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.triclass.dm.Heartbeat) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long schoolId_ ;
    /**
     * <pre>
     * 学校编号
     * </pre>
     *
     * <code>int64 schoolId = 1;</code>
     * @return The schoolId.
     */
    @java.lang.Override
    public long getSchoolId() {
      return schoolId_;
    }
    /**
     * <pre>
     * 学校编号
     * </pre>
     *
     * <code>int64 schoolId = 1;</code>
     * @param value The schoolId to set.
     * @return This builder for chaining.
     */
    public Builder setSchoolId(long value) {
      
      schoolId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 学校编号
     * </pre>
     *
     * <code>int64 schoolId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchoolId() {
      
      schoolId_ = 0L;
      onChanged();
      return this;
    }

    private int manufacturer_ = 0;
    /**
     * <pre>
     * 厂商
     * </pre>
     *
     * <code>.triclass.manufacturer.Manufacturer manufacturer = 2;</code>
     * @return The enum numeric value on the wire for manufacturer.
     */
    @java.lang.Override public int getManufacturerValue() {
      return manufacturer_;
    }
    /**
     * <pre>
     * 厂商
     * </pre>
     *
     * <code>.triclass.manufacturer.Manufacturer manufacturer = 2;</code>
     * @param value The enum numeric value on the wire for manufacturer to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturerValue(int value) {
      
      manufacturer_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 厂商
     * </pre>
     *
     * <code>.triclass.manufacturer.Manufacturer manufacturer = 2;</code>
     * @return The manufacturer.
     */
    @java.lang.Override
    public com.triclass.Manufacturer getManufacturer() {
      @SuppressWarnings("deprecation")
      com.triclass.Manufacturer result = com.triclass.Manufacturer.valueOf(manufacturer_);
      return result == null ? com.triclass.Manufacturer.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 厂商
     * </pre>
     *
     * <code>.triclass.manufacturer.Manufacturer manufacturer = 2;</code>
     * @param value The manufacturer to set.
     * @return This builder for chaining.
     */
    public Builder setManufacturer(com.triclass.Manufacturer value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      manufacturer_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 厂商
     * </pre>
     *
     * <code>.triclass.manufacturer.Manufacturer manufacturer = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearManufacturer() {
      
      manufacturer_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object sn_ = "";
    /**
     * <pre>
     * 设备序列号
     * </pre>
     *
     * <code>string sn = 3;</code>
     * @return The sn.
     */
    public java.lang.String getSn() {
      java.lang.Object ref = sn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备序列号
     * </pre>
     *
     * <code>string sn = 3;</code>
     * @return The bytes for sn.
     */
    public com.google.protobuf.ByteString
        getSnBytes() {
      java.lang.Object ref = sn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备序列号
     * </pre>
     *
     * <code>string sn = 3;</code>
     * @param value The sn to set.
     * @return This builder for chaining.
     */
    public Builder setSn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备序列号
     * </pre>
     *
     * <code>string sn = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSn() {
      
      sn_ = getDefaultInstance().getSn();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备序列号
     * </pre>
     *
     * <code>string sn = 3;</code>
     * @param value The bytes for sn to set.
     * @return This builder for chaining.
     */
    public Builder setSnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sn_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <pre>
     * 设备状态
     * </pre>
     *
     * <code>.triclass.system.status.SystemStatus status = 4;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <pre>
     * 设备状态
     * </pre>
     *
     * <code>.triclass.system.status.SystemStatus status = 4;</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备状态
     * </pre>
     *
     * <code>.triclass.system.status.SystemStatus status = 4;</code>
     * @return The status.
     */
    @java.lang.Override
    public com.triclass.SystemStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.triclass.SystemStatus result = com.triclass.SystemStatus.valueOf(status_);
      return result == null ? com.triclass.SystemStatus.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * 设备状态
     * </pre>
     *
     * <code>.triclass.system.status.SystemStatus status = 4;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.triclass.SystemStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备状态
     * </pre>
     *
     * <code>.triclass.system.status.SystemStatus status = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:triclass.dm.Heartbeat)
  }

  // @@protoc_insertion_point(class_scope:triclass.dm.Heartbeat)
  private static final com.triclass.dm.Heartbeat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.triclass.dm.Heartbeat();
  }

  public static com.triclass.dm.Heartbeat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Heartbeat>
      PARSER = new com.google.protobuf.AbstractParser<Heartbeat>() {
    @java.lang.Override
    public Heartbeat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Heartbeat(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Heartbeat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Heartbeat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.triclass.dm.Heartbeat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

