// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: manufacturer.proto

package com.triclass;

public final class ManufacturerOuterClass {
  private ManufacturerOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022manufacturer.proto\022\025triclass.manufactu" +
      "rer*$\n\014Manufacturer\022\013\n\007UNKNOWN\020\000\022\007\n\003VHD\020" +
      "\001B\034\n\014com.triclassP\001Z\n.;triclassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
