// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: switch.proto

package com.triclass;

public final class SwitchOuterClass {
  private SwitchOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014switch.proto\022\017triclass.switch*\031\n\006Switc" +
      "h\022\006\n\002ON\020\000\022\007\n\003OFF\020\001B:\n\014com.triclassP\001Z(gi" +
      "thub.com/triclass/protocol-go;triclassb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
