// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_status.proto

package com.triclass;

public final class SystemStatusOuterClass {
  private SystemStatusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023system_status.proto\022\026triclass.system.s" +
      "tatus*9\n\014SystemStatus\022\013\n\007UNKNOWN\020\000\022\007\n\003OF" +
      "F\020\001\022\013\n\007STANDBY\020\002\022\006\n\002ON\020\003B:\n\014com.triclass" +
      "P\001Z(github.com/triclass/protocol-go;tric" +
      "lassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
