// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_status.proto

package com.triclass;

public final class SystemStatusOuterClass {
  private SystemStatusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023system_status.proto\022\026triclass.system.s" +
      "tatus*,\n\014SystemStatus\022\006\n\002ON\020\000\022\007\n\003OFF\020\001\022\013" +
      "\n\007STANDBY\020\002B\034\n\014com.triclassP\001Z\n.;triclas" +
      "sb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
