// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_status.proto

package com.triclass;

/**
 * <pre>
 * 系统状态
 * </pre>
 *
 * Protobuf enum {@code triclass.system.status.SystemStatus}
 */
public enum SystemStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * 未知状态
   * </pre>
   *
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <pre>
   * 关机
   * </pre>
   *
   * <code>OFF = 1;</code>
   */
  OFF(1),
  /**
   * <pre>
   * 待机
   * </pre>
   *
   * <code>STANDBY = 2;</code>
   */
  STANDBY(2),
  /**
   * <pre>
   * 开机
   * </pre>
   *
   * <code>ON = 3;</code>
   */
  ON(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * 未知状态
   * </pre>
   *
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <pre>
   * 关机
   * </pre>
   *
   * <code>OFF = 1;</code>
   */
  public static final int OFF_VALUE = 1;
  /**
   * <pre>
   * 待机
   * </pre>
   *
   * <code>STANDBY = 2;</code>
   */
  public static final int STANDBY_VALUE = 2;
  /**
   * <pre>
   * 开机
   * </pre>
   *
   * <code>ON = 3;</code>
   */
  public static final int ON_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SystemStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static SystemStatus forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return OFF;
      case 2: return STANDBY;
      case 3: return ON;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SystemStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SystemStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SystemStatus>() {
          public SystemStatus findValueByNumber(int number) {
            return SystemStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.triclass.SystemStatusOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final SystemStatus[] VALUES = values();

  public static SystemStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private SystemStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:triclass.system.status.SystemStatus)
}

