// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timestamp.proto

package com.triclass;

public final class TimestampOuterClass {
  private TimestampOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_triclass_timestamp_Timestamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_triclass_timestamp_Timestamp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017timestamp.proto\022\022triclass.timestamp\"\'\n" +
      "\tTimestamp\022\r\n\005start\030\001 \001(\003\022\013\n\003end\030\002 \001(\003B:" +
      "\n\014com.triclassP\001Z(github.com/triclass/pr" +
      "otocol-go;triclassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_triclass_timestamp_Timestamp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_triclass_timestamp_Timestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_triclass_timestamp_Timestamp_descriptor,
        new java.lang.String[] { "Start", "End", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
