// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timestamp.proto

package com.triclass;

public interface TimestampOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.timestamp.Timestamp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>int64 start = 1;</code>
   * @return The start.
   */
  long getStart();

  /**
   * <pre>
   * 结束时间
   * </pre>
   *
   * <code>int64 end = 2;</code>
   * @return The end.
   */
  long getEnd();
}
