// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/action.proto

package com.triclass.hardware;

public final class ActionOuterClass {
  private ActionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_triclass_hardware_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_triclass_hardware_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025hardware/action.proto\022\021triclass.hardwa" +
      "re\032\025hardware/course.proto\032\025hardware/syst" +
      "em.proto\"\177\n\006Action\022+\n\006course\030\001 \001(\0132\031.tri" +
      "class.hardware.CourseH\000\022+\n\006system\030\002 \001(\0132" +
      "\031.triclass.hardware.SystemH\000\022\021\n\ttimestam" +
      "p\030\003 \001(\003B\010\n\006actionB.\n\025com.triclass.hardwa" +
      "reP\001Z\023./hardware;hardwareb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.triclass.hardware.CourseOuterClass.getDescriptor(),
          com.triclass.hardware.SystemOuterClass.getDescriptor(),
        });
    internal_static_triclass_hardware_Action_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_triclass_hardware_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_triclass_hardware_Action_descriptor,
        new java.lang.String[] { "Course", "System", "Timestamp", "Action", });
    com.triclass.hardware.CourseOuterClass.getDescriptor();
    com.triclass.hardware.SystemOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
