// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/action.proto

package com.triclass.hardware;

/**
 * <pre>
 * 硬件协议最顶层
 * </pre>
 *
 * Protobuf type {@code triclass.hardware.Action}
 */
public final class Action extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:triclass.hardware.Action)
    ActionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Action.newBuilder() to construct.
  private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Action() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Action();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Action(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.triclass.hardware.Course.Builder subBuilder = null;
            if (actionCase_ == 1) {
              subBuilder = ((com.triclass.hardware.Course) action_).toBuilder();
            }
            action_ =
                input.readMessage(com.triclass.hardware.Course.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.triclass.hardware.Course) action_);
              action_ = subBuilder.buildPartial();
            }
            actionCase_ = 1;
            break;
          }
          case 18: {
            com.triclass.hardware.System.Builder subBuilder = null;
            if (actionCase_ == 2) {
              subBuilder = ((com.triclass.hardware.System) action_).toBuilder();
            }
            action_ =
                input.readMessage(com.triclass.hardware.System.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.triclass.hardware.System) action_);
              action_ = subBuilder.buildPartial();
            }
            actionCase_ = 2;
            break;
          }
          case 24: {

            timestamp_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.triclass.hardware.ActionOuterClass.internal_static_triclass_hardware_Action_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.triclass.hardware.ActionOuterClass.internal_static_triclass_hardware_Action_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.triclass.hardware.Action.class, com.triclass.hardware.Action.Builder.class);
  }

  private int actionCase_ = 0;
  private java.lang.Object action_;
  public enum ActionCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    COURSE(1),
    SYSTEM(2),
    ACTION_NOT_SET(0);
    private final int value;
    private ActionCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ActionCase valueOf(int value) {
      return forNumber(value);
    }

    public static ActionCase forNumber(int value) {
      switch (value) {
        case 1: return COURSE;
        case 2: return SYSTEM;
        case 0: return ACTION_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ActionCase
  getActionCase() {
    return ActionCase.forNumber(
        actionCase_);
  }

  public static final int COURSE_FIELD_NUMBER = 1;
  /**
   * <pre>
   * 会议控制
   * </pre>
   *
   * <code>.triclass.hardware.Course course = 1;</code>
   * @return Whether the course field is set.
   */
  @java.lang.Override
  public boolean hasCourse() {
    return actionCase_ == 1;
  }
  /**
   * <pre>
   * 会议控制
   * </pre>
   *
   * <code>.triclass.hardware.Course course = 1;</code>
   * @return The course.
   */
  @java.lang.Override
  public com.triclass.hardware.Course getCourse() {
    if (actionCase_ == 1) {
       return (com.triclass.hardware.Course) action_;
    }
    return com.triclass.hardware.Course.getDefaultInstance();
  }
  /**
   * <pre>
   * 会议控制
   * </pre>
   *
   * <code>.triclass.hardware.Course course = 1;</code>
   */
  @java.lang.Override
  public com.triclass.hardware.CourseOrBuilder getCourseOrBuilder() {
    if (actionCase_ == 1) {
       return (com.triclass.hardware.Course) action_;
    }
    return com.triclass.hardware.Course.getDefaultInstance();
  }

  public static final int SYSTEM_FIELD_NUMBER = 2;
  /**
   * <pre>
   * 系统控制
   * </pre>
   *
   * <code>.triclass.hardware.System system = 2;</code>
   * @return Whether the system field is set.
   */
  @java.lang.Override
  public boolean hasSystem() {
    return actionCase_ == 2;
  }
  /**
   * <pre>
   * 系统控制
   * </pre>
   *
   * <code>.triclass.hardware.System system = 2;</code>
   * @return The system.
   */
  @java.lang.Override
  public com.triclass.hardware.System getSystem() {
    if (actionCase_ == 2) {
       return (com.triclass.hardware.System) action_;
    }
    return com.triclass.hardware.System.getDefaultInstance();
  }
  /**
   * <pre>
   * 系统控制
   * </pre>
   *
   * <code>.triclass.hardware.System system = 2;</code>
   */
  @java.lang.Override
  public com.triclass.hardware.SystemOrBuilder getSystemOrBuilder() {
    if (actionCase_ == 2) {
       return (com.triclass.hardware.System) action_;
    }
    return com.triclass.hardware.System.getDefaultInstance();
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_;
  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (actionCase_ == 1) {
      output.writeMessage(1, (com.triclass.hardware.Course) action_);
    }
    if (actionCase_ == 2) {
      output.writeMessage(2, (com.triclass.hardware.System) action_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(3, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (actionCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, (com.triclass.hardware.Course) action_);
    }
    if (actionCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.triclass.hardware.System) action_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.triclass.hardware.Action)) {
      return super.equals(obj);
    }
    com.triclass.hardware.Action other = (com.triclass.hardware.Action) obj;

    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (!getActionCase().equals(other.getActionCase())) return false;
    switch (actionCase_) {
      case 1:
        if (!getCourse()
            .equals(other.getCourse())) return false;
        break;
      case 2:
        if (!getSystem()
            .equals(other.getSystem())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    switch (actionCase_) {
      case 1:
        hash = (37 * hash) + COURSE_FIELD_NUMBER;
        hash = (53 * hash) + getCourse().hashCode();
        break;
      case 2:
        hash = (37 * hash) + SYSTEM_FIELD_NUMBER;
        hash = (53 * hash) + getSystem().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.triclass.hardware.Action parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.hardware.Action parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.hardware.Action parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.hardware.Action parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.hardware.Action parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.hardware.Action parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.hardware.Action parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.triclass.hardware.Action parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.triclass.hardware.Action parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.triclass.hardware.Action parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.triclass.hardware.Action parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.triclass.hardware.Action parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.triclass.hardware.Action prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 硬件协议最顶层
   * </pre>
   *
   * Protobuf type {@code triclass.hardware.Action}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:triclass.hardware.Action)
      com.triclass.hardware.ActionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.triclass.hardware.ActionOuterClass.internal_static_triclass_hardware_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.triclass.hardware.ActionOuterClass.internal_static_triclass_hardware_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.triclass.hardware.Action.class, com.triclass.hardware.Action.Builder.class);
    }

    // Construct using com.triclass.hardware.Action.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      timestamp_ = 0L;

      actionCase_ = 0;
      action_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.triclass.hardware.ActionOuterClass.internal_static_triclass_hardware_Action_descriptor;
    }

    @java.lang.Override
    public com.triclass.hardware.Action getDefaultInstanceForType() {
      return com.triclass.hardware.Action.getDefaultInstance();
    }

    @java.lang.Override
    public com.triclass.hardware.Action build() {
      com.triclass.hardware.Action result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.triclass.hardware.Action buildPartial() {
      com.triclass.hardware.Action result = new com.triclass.hardware.Action(this);
      if (actionCase_ == 1) {
        if (courseBuilder_ == null) {
          result.action_ = action_;
        } else {
          result.action_ = courseBuilder_.build();
        }
      }
      if (actionCase_ == 2) {
        if (systemBuilder_ == null) {
          result.action_ = action_;
        } else {
          result.action_ = systemBuilder_.build();
        }
      }
      result.timestamp_ = timestamp_;
      result.actionCase_ = actionCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.triclass.hardware.Action) {
        return mergeFrom((com.triclass.hardware.Action)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.triclass.hardware.Action other) {
      if (other == com.triclass.hardware.Action.getDefaultInstance()) return this;
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      switch (other.getActionCase()) {
        case COURSE: {
          mergeCourse(other.getCourse());
          break;
        }
        case SYSTEM: {
          mergeSystem(other.getSystem());
          break;
        }
        case ACTION_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.triclass.hardware.Action parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.triclass.hardware.Action) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int actionCase_ = 0;
    private java.lang.Object action_;
    public ActionCase
        getActionCase() {
      return ActionCase.forNumber(
          actionCase_);
    }

    public Builder clearAction() {
      actionCase_ = 0;
      action_ = null;
      onChanged();
      return this;
    }


    private com.google.protobuf.SingleFieldBuilderV3<
        com.triclass.hardware.Course, com.triclass.hardware.Course.Builder, com.triclass.hardware.CourseOrBuilder> courseBuilder_;
    /**
     * <pre>
     * 会议控制
     * </pre>
     *
     * <code>.triclass.hardware.Course course = 1;</code>
     * @return Whether the course field is set.
     */
    @java.lang.Override
    public boolean hasCourse() {
      return actionCase_ == 1;
    }
    /**
     * <pre>
     * 会议控制
     * </pre>
     *
     * <code>.triclass.hardware.Course course = 1;</code>
     * @return The course.
     */
    @java.lang.Override
    public com.triclass.hardware.Course getCourse() {
      if (courseBuilder_ == null) {
        if (actionCase_ == 1) {
          return (com.triclass.hardware.Course) action_;
        }
        return com.triclass.hardware.Course.getDefaultInstance();
      } else {
        if (actionCase_ == 1) {
          return courseBuilder_.getMessage();
        }
        return com.triclass.hardware.Course.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 会议控制
     * </pre>
     *
     * <code>.triclass.hardware.Course course = 1;</code>
     */
    public Builder setCourse(com.triclass.hardware.Course value) {
      if (courseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        action_ = value;
        onChanged();
      } else {
        courseBuilder_.setMessage(value);
      }
      actionCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * 会议控制
     * </pre>
     *
     * <code>.triclass.hardware.Course course = 1;</code>
     */
    public Builder setCourse(
        com.triclass.hardware.Course.Builder builderForValue) {
      if (courseBuilder_ == null) {
        action_ = builderForValue.build();
        onChanged();
      } else {
        courseBuilder_.setMessage(builderForValue.build());
      }
      actionCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * 会议控制
     * </pre>
     *
     * <code>.triclass.hardware.Course course = 1;</code>
     */
    public Builder mergeCourse(com.triclass.hardware.Course value) {
      if (courseBuilder_ == null) {
        if (actionCase_ == 1 &&
            action_ != com.triclass.hardware.Course.getDefaultInstance()) {
          action_ = com.triclass.hardware.Course.newBuilder((com.triclass.hardware.Course) action_)
              .mergeFrom(value).buildPartial();
        } else {
          action_ = value;
        }
        onChanged();
      } else {
        if (actionCase_ == 1) {
          courseBuilder_.mergeFrom(value);
        }
        courseBuilder_.setMessage(value);
      }
      actionCase_ = 1;
      return this;
    }
    /**
     * <pre>
     * 会议控制
     * </pre>
     *
     * <code>.triclass.hardware.Course course = 1;</code>
     */
    public Builder clearCourse() {
      if (courseBuilder_ == null) {
        if (actionCase_ == 1) {
          actionCase_ = 0;
          action_ = null;
          onChanged();
        }
      } else {
        if (actionCase_ == 1) {
          actionCase_ = 0;
          action_ = null;
        }
        courseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 会议控制
     * </pre>
     *
     * <code>.triclass.hardware.Course course = 1;</code>
     */
    public com.triclass.hardware.Course.Builder getCourseBuilder() {
      return getCourseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 会议控制
     * </pre>
     *
     * <code>.triclass.hardware.Course course = 1;</code>
     */
    @java.lang.Override
    public com.triclass.hardware.CourseOrBuilder getCourseOrBuilder() {
      if ((actionCase_ == 1) && (courseBuilder_ != null)) {
        return courseBuilder_.getMessageOrBuilder();
      } else {
        if (actionCase_ == 1) {
          return (com.triclass.hardware.Course) action_;
        }
        return com.triclass.hardware.Course.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 会议控制
     * </pre>
     *
     * <code>.triclass.hardware.Course course = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.triclass.hardware.Course, com.triclass.hardware.Course.Builder, com.triclass.hardware.CourseOrBuilder> 
        getCourseFieldBuilder() {
      if (courseBuilder_ == null) {
        if (!(actionCase_ == 1)) {
          action_ = com.triclass.hardware.Course.getDefaultInstance();
        }
        courseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.triclass.hardware.Course, com.triclass.hardware.Course.Builder, com.triclass.hardware.CourseOrBuilder>(
                (com.triclass.hardware.Course) action_,
                getParentForChildren(),
                isClean());
        action_ = null;
      }
      actionCase_ = 1;
      onChanged();;
      return courseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.triclass.hardware.System, com.triclass.hardware.System.Builder, com.triclass.hardware.SystemOrBuilder> systemBuilder_;
    /**
     * <pre>
     * 系统控制
     * </pre>
     *
     * <code>.triclass.hardware.System system = 2;</code>
     * @return Whether the system field is set.
     */
    @java.lang.Override
    public boolean hasSystem() {
      return actionCase_ == 2;
    }
    /**
     * <pre>
     * 系统控制
     * </pre>
     *
     * <code>.triclass.hardware.System system = 2;</code>
     * @return The system.
     */
    @java.lang.Override
    public com.triclass.hardware.System getSystem() {
      if (systemBuilder_ == null) {
        if (actionCase_ == 2) {
          return (com.triclass.hardware.System) action_;
        }
        return com.triclass.hardware.System.getDefaultInstance();
      } else {
        if (actionCase_ == 2) {
          return systemBuilder_.getMessage();
        }
        return com.triclass.hardware.System.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 系统控制
     * </pre>
     *
     * <code>.triclass.hardware.System system = 2;</code>
     */
    public Builder setSystem(com.triclass.hardware.System value) {
      if (systemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        action_ = value;
        onChanged();
      } else {
        systemBuilder_.setMessage(value);
      }
      actionCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 系统控制
     * </pre>
     *
     * <code>.triclass.hardware.System system = 2;</code>
     */
    public Builder setSystem(
        com.triclass.hardware.System.Builder builderForValue) {
      if (systemBuilder_ == null) {
        action_ = builderForValue.build();
        onChanged();
      } else {
        systemBuilder_.setMessage(builderForValue.build());
      }
      actionCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 系统控制
     * </pre>
     *
     * <code>.triclass.hardware.System system = 2;</code>
     */
    public Builder mergeSystem(com.triclass.hardware.System value) {
      if (systemBuilder_ == null) {
        if (actionCase_ == 2 &&
            action_ != com.triclass.hardware.System.getDefaultInstance()) {
          action_ = com.triclass.hardware.System.newBuilder((com.triclass.hardware.System) action_)
              .mergeFrom(value).buildPartial();
        } else {
          action_ = value;
        }
        onChanged();
      } else {
        if (actionCase_ == 2) {
          systemBuilder_.mergeFrom(value);
        }
        systemBuilder_.setMessage(value);
      }
      actionCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * 系统控制
     * </pre>
     *
     * <code>.triclass.hardware.System system = 2;</code>
     */
    public Builder clearSystem() {
      if (systemBuilder_ == null) {
        if (actionCase_ == 2) {
          actionCase_ = 0;
          action_ = null;
          onChanged();
        }
      } else {
        if (actionCase_ == 2) {
          actionCase_ = 0;
          action_ = null;
        }
        systemBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * 系统控制
     * </pre>
     *
     * <code>.triclass.hardware.System system = 2;</code>
     */
    public com.triclass.hardware.System.Builder getSystemBuilder() {
      return getSystemFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 系统控制
     * </pre>
     *
     * <code>.triclass.hardware.System system = 2;</code>
     */
    @java.lang.Override
    public com.triclass.hardware.SystemOrBuilder getSystemOrBuilder() {
      if ((actionCase_ == 2) && (systemBuilder_ != null)) {
        return systemBuilder_.getMessageOrBuilder();
      } else {
        if (actionCase_ == 2) {
          return (com.triclass.hardware.System) action_;
        }
        return com.triclass.hardware.System.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * 系统控制
     * </pre>
     *
     * <code>.triclass.hardware.System system = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.triclass.hardware.System, com.triclass.hardware.System.Builder, com.triclass.hardware.SystemOrBuilder> 
        getSystemFieldBuilder() {
      if (systemBuilder_ == null) {
        if (!(actionCase_ == 2)) {
          action_ = com.triclass.hardware.System.getDefaultInstance();
        }
        systemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.triclass.hardware.System, com.triclass.hardware.System.Builder, com.triclass.hardware.SystemOrBuilder>(
                (com.triclass.hardware.System) action_,
                getParentForChildren(),
                isClean());
        action_ = null;
      }
      actionCase_ = 2;
      onChanged();;
      return systemBuilder_;
    }

    private long timestamp_ ;
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 时间戳
     * </pre>
     *
     * <code>int64 timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:triclass.hardware.Action)
  }

  // @@protoc_insertion_point(class_scope:triclass.hardware.Action)
  private static final com.triclass.hardware.Action DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.triclass.hardware.Action();
  }

  public static com.triclass.hardware.Action getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Action>
      PARSER = new com.google.protobuf.AbstractParser<Action>() {
    @java.lang.Override
    public Action parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Action(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Action> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Action> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.triclass.hardware.Action getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

