// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/action.proto

package com.triclass.hardware;

public interface ActionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.hardware.Action)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 会议控制
   * </pre>
   *
   * <code>.triclass.hardware.Course course = 1;</code>
   * @return Whether the course field is set.
   */
  boolean hasCourse();
  /**
   * <pre>
   * 会议控制
   * </pre>
   *
   * <code>.triclass.hardware.Course course = 1;</code>
   * @return The course.
   */
  com.triclass.hardware.Course getCourse();
  /**
   * <pre>
   * 会议控制
   * </pre>
   *
   * <code>.triclass.hardware.Course course = 1;</code>
   */
  com.triclass.hardware.CourseOrBuilder getCourseOrBuilder();

  /**
   * <pre>
   * 系统控制
   * </pre>
   *
   * <code>.triclass.hardware.System system = 2;</code>
   * @return Whether the system field is set.
   */
  boolean hasSystem();
  /**
   * <pre>
   * 系统控制
   * </pre>
   *
   * <code>.triclass.hardware.System system = 2;</code>
   * @return The system.
   */
  com.triclass.hardware.System getSystem();
  /**
   * <pre>
   * 系统控制
   * </pre>
   *
   * <code>.triclass.hardware.System system = 2;</code>
   */
  com.triclass.hardware.SystemOrBuilder getSystemOrBuilder();

  /**
   * <pre>
   * 时间戳
   * </pre>
   *
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  public com.triclass.hardware.Action.ActionCase getActionCase();
}
