// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/course_audio.proto

package com.triclass.hardware;

public interface AudioOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.hardware.Audio)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 音量
   * </pre>
   *
   * <code>int32 volume = 1;</code>
   * @return The volume.
   */
  int getVolume();
}
