// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/course_start.proto

package com.triclass.hardware;

public final class CourseStart {
  private CourseStart() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_triclass_hardware_Start_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_triclass_hardware_Start_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033hardware/course_start.proto\022\021triclass." +
      "hardware\032\036hardware/course_password.proto" +
      "\032\017timestamp.proto\"\251\001\n\005Start\022\n\n\002id\030\001 \001(\t\022" +
      "2\n\010password\030\002 \001(\0132\033.triclass.hardware.Pa" +
      "sswordH\000\210\001\001\022\017\n\007subject\030\003 \001(\t\0220\n\ttimestam" +
      "p\030\004 \001(\0132\035.triclass.timestamp.Timestamp\022\020" +
      "\n\010push_url\030\005 \003(\tB\013\n\t_passwordB.\n\025com.tri" +
      "class.hardwareP\001Z\023./hardware;hardwareb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.triclass.hardware.CoursePassword.getDescriptor(),
          com.triclass.TimestampOuterClass.getDescriptor(),
        });
    internal_static_triclass_hardware_Start_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_triclass_hardware_Start_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_triclass_hardware_Start_descriptor,
        new java.lang.String[] { "Id", "Password", "Subject", "Timestamp", "PushUrl", "Password", });
    com.triclass.hardware.CoursePassword.getDescriptor();
    com.triclass.TimestampOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
