// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/course_audio.proto

package com.triclass.hardware;

public final class CourseAudio {
  private CourseAudio() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_triclass_hardware_Audio_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_triclass_hardware_Audio_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033hardware/course_audio.proto\022\021triclass." +
      "hardware\"\027\n\005Audio\022\016\n\006volume\030\001 \001(\005B.\n\025com" +
      ".triclass.hardwareP\001Z\023./hardware;hardwar" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_triclass_hardware_Audio_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_triclass_hardware_Audio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_triclass_hardware_Audio_descriptor,
        new java.lang.String[] { "Volume", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
