// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/course.proto

package com.triclass.hardware;

public interface CourseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.hardware.Course)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 开始会议
   * 收到该请求后，硬件设备应该立即调起摄像头、麦克风等设备且立即加入会议
   * </pre>
   *
   * <code>.triclass.hardware.Start start = 1;</code>
   * @return Whether the start field is set.
   */
  boolean hasStart();
  /**
   * <pre>
   * 开始会议
   * 收到该请求后，硬件设备应该立即调起摄像头、麦克风等设备且立即加入会议
   * </pre>
   *
   * <code>.triclass.hardware.Start start = 1;</code>
   * @return The start.
   */
  com.triclass.hardware.Start getStart();
  /**
   * <pre>
   * 开始会议
   * 收到该请求后，硬件设备应该立即调起摄像头、麦克风等设备且立即加入会议
   * </pre>
   *
   * <code>.triclass.hardware.Start start = 1;</code>
   */
  com.triclass.hardware.StartOrBuilder getStartOrBuilder();

  /**
   * <pre>
   * 结束会议
   * </pre>
   *
   * <code>.triclass.hardware.Terminate terminate = 2;</code>
   * @return Whether the terminate field is set.
   */
  boolean hasTerminate();
  /**
   * <pre>
   * 结束会议
   * </pre>
   *
   * <code>.triclass.hardware.Terminate terminate = 2;</code>
   * @return The terminate.
   */
  com.triclass.hardware.Terminate getTerminate();
  /**
   * <pre>
   * 结束会议
   * </pre>
   *
   * <code>.triclass.hardware.Terminate terminate = 2;</code>
   */
  com.triclass.hardware.TerminateOrBuilder getTerminateOrBuilder();

  /**
   * <pre>
   * 视频
   * </pre>
   *
   * <code>.triclass.hardware.Video video = 3;</code>
   * @return Whether the video field is set.
   */
  boolean hasVideo();
  /**
   * <pre>
   * 视频
   * </pre>
   *
   * <code>.triclass.hardware.Video video = 3;</code>
   * @return The video.
   */
  com.triclass.hardware.Video getVideo();
  /**
   * <pre>
   * 视频
   * </pre>
   *
   * <code>.triclass.hardware.Video video = 3;</code>
   */
  com.triclass.hardware.VideoOrBuilder getVideoOrBuilder();

  /**
   * <pre>
   * 麦克风
   * </pre>
   *
   * <code>.triclass.hardware.Microphone microphone = 4;</code>
   * @return Whether the microphone field is set.
   */
  boolean hasMicrophone();
  /**
   * <pre>
   * 麦克风
   * </pre>
   *
   * <code>.triclass.hardware.Microphone microphone = 4;</code>
   * @return The microphone.
   */
  com.triclass.hardware.Microphone getMicrophone();
  /**
   * <pre>
   * 麦克风
   * </pre>
   *
   * <code>.triclass.hardware.Microphone microphone = 4;</code>
   */
  com.triclass.hardware.MicrophoneOrBuilder getMicrophoneOrBuilder();

  /**
   * <pre>
   * 音频
   * </pre>
   *
   * <code>.triclass.hardware.Audio audio = 5;</code>
   * @return Whether the audio field is set.
   */
  boolean hasAudio();
  /**
   * <pre>
   * 音频
   * </pre>
   *
   * <code>.triclass.hardware.Audio audio = 5;</code>
   * @return The audio.
   */
  com.triclass.hardware.Audio getAudio();
  /**
   * <pre>
   * 音频
   * </pre>
   *
   * <code>.triclass.hardware.Audio audio = 5;</code>
   */
  com.triclass.hardware.AudioOrBuilder getAudioOrBuilder();

  public com.triclass.hardware.Course.ActionCase getActionCase();
}
