// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/course_microphone.proto

package com.triclass.hardware;

public interface MicrophoneOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.hardware.Microphone)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>.triclass.switch.Switch status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * 状态
   * </pre>
   *
   * <code>.triclass.switch.Switch status = 1;</code>
   * @return The status.
   */
  com.triclass.Switch getStatus();
}
