// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/course_password.proto

package com.triclass.hardware;

/**
 * <pre>
 * 密码设置
 * </pre>
 *
 * Protobuf type {@code triclass.hardware.Password}
 */
public final class Password extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:triclass.hardware.Password)
    PasswordOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Password.newBuilder() to construct.
  private Password(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Password() {
    chairman_ = "";
    participant_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Password();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Password(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            chairman_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            participant_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.triclass.hardware.CoursePassword.internal_static_triclass_hardware_Password_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.triclass.hardware.CoursePassword.internal_static_triclass_hardware_Password_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.triclass.hardware.Password.class, com.triclass.hardware.Password.Builder.class);
  }

  public static final int CHAIRMAN_FIELD_NUMBER = 1;
  private volatile java.lang.Object chairman_;
  /**
   * <pre>
   * 主讲人密码
   * </pre>
   *
   * <code>string chairman = 1;</code>
   * @return The chairman.
   */
  @java.lang.Override
  public java.lang.String getChairman() {
    java.lang.Object ref = chairman_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      chairman_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 主讲人密码
   * </pre>
   *
   * <code>string chairman = 1;</code>
   * @return The bytes for chairman.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getChairmanBytes() {
    java.lang.Object ref = chairman_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      chairman_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTICIPANT_FIELD_NUMBER = 2;
  private volatile java.lang.Object participant_;
  /**
   * <pre>
   * 参会人密码
   * </pre>
   *
   * <code>string participant = 2;</code>
   * @return The participant.
   */
  @java.lang.Override
  public java.lang.String getParticipant() {
    java.lang.Object ref = participant_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      participant_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 参会人密码
   * </pre>
   *
   * <code>string participant = 2;</code>
   * @return The bytes for participant.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParticipantBytes() {
    java.lang.Object ref = participant_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      participant_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getChairmanBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chairman_);
    }
    if (!getParticipantBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, participant_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getChairmanBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chairman_);
    }
    if (!getParticipantBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, participant_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.triclass.hardware.Password)) {
      return super.equals(obj);
    }
    com.triclass.hardware.Password other = (com.triclass.hardware.Password) obj;

    if (!getChairman()
        .equals(other.getChairman())) return false;
    if (!getParticipant()
        .equals(other.getParticipant())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CHAIRMAN_FIELD_NUMBER;
    hash = (53 * hash) + getChairman().hashCode();
    hash = (37 * hash) + PARTICIPANT_FIELD_NUMBER;
    hash = (53 * hash) + getParticipant().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.triclass.hardware.Password parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.hardware.Password parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.hardware.Password parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.hardware.Password parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.hardware.Password parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.triclass.hardware.Password parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.triclass.hardware.Password parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.triclass.hardware.Password parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.triclass.hardware.Password parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.triclass.hardware.Password parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.triclass.hardware.Password parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.triclass.hardware.Password parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.triclass.hardware.Password prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 密码设置
   * </pre>
   *
   * Protobuf type {@code triclass.hardware.Password}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:triclass.hardware.Password)
      com.triclass.hardware.PasswordOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.triclass.hardware.CoursePassword.internal_static_triclass_hardware_Password_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.triclass.hardware.CoursePassword.internal_static_triclass_hardware_Password_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.triclass.hardware.Password.class, com.triclass.hardware.Password.Builder.class);
    }

    // Construct using com.triclass.hardware.Password.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      chairman_ = "";

      participant_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.triclass.hardware.CoursePassword.internal_static_triclass_hardware_Password_descriptor;
    }

    @java.lang.Override
    public com.triclass.hardware.Password getDefaultInstanceForType() {
      return com.triclass.hardware.Password.getDefaultInstance();
    }

    @java.lang.Override
    public com.triclass.hardware.Password build() {
      com.triclass.hardware.Password result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.triclass.hardware.Password buildPartial() {
      com.triclass.hardware.Password result = new com.triclass.hardware.Password(this);
      result.chairman_ = chairman_;
      result.participant_ = participant_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.triclass.hardware.Password) {
        return mergeFrom((com.triclass.hardware.Password)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.triclass.hardware.Password other) {
      if (other == com.triclass.hardware.Password.getDefaultInstance()) return this;
      if (!other.getChairman().isEmpty()) {
        chairman_ = other.chairman_;
        onChanged();
      }
      if (!other.getParticipant().isEmpty()) {
        participant_ = other.participant_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.triclass.hardware.Password parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.triclass.hardware.Password) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object chairman_ = "";
    /**
     * <pre>
     * 主讲人密码
     * </pre>
     *
     * <code>string chairman = 1;</code>
     * @return The chairman.
     */
    public java.lang.String getChairman() {
      java.lang.Object ref = chairman_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chairman_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 主讲人密码
     * </pre>
     *
     * <code>string chairman = 1;</code>
     * @return The bytes for chairman.
     */
    public com.google.protobuf.ByteString
        getChairmanBytes() {
      java.lang.Object ref = chairman_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chairman_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 主讲人密码
     * </pre>
     *
     * <code>string chairman = 1;</code>
     * @param value The chairman to set.
     * @return This builder for chaining.
     */
    public Builder setChairman(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      chairman_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 主讲人密码
     * </pre>
     *
     * <code>string chairman = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearChairman() {
      
      chairman_ = getDefaultInstance().getChairman();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 主讲人密码
     * </pre>
     *
     * <code>string chairman = 1;</code>
     * @param value The bytes for chairman to set.
     * @return This builder for chaining.
     */
    public Builder setChairmanBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      chairman_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object participant_ = "";
    /**
     * <pre>
     * 参会人密码
     * </pre>
     *
     * <code>string participant = 2;</code>
     * @return The participant.
     */
    public java.lang.String getParticipant() {
      java.lang.Object ref = participant_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        participant_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 参会人密码
     * </pre>
     *
     * <code>string participant = 2;</code>
     * @return The bytes for participant.
     */
    public com.google.protobuf.ByteString
        getParticipantBytes() {
      java.lang.Object ref = participant_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        participant_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 参会人密码
     * </pre>
     *
     * <code>string participant = 2;</code>
     * @param value The participant to set.
     * @return This builder for chaining.
     */
    public Builder setParticipant(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      participant_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参会人密码
     * </pre>
     *
     * <code>string participant = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearParticipant() {
      
      participant_ = getDefaultInstance().getParticipant();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 参会人密码
     * </pre>
     *
     * <code>string participant = 2;</code>
     * @param value The bytes for participant to set.
     * @return This builder for chaining.
     */
    public Builder setParticipantBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      participant_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:triclass.hardware.Password)
  }

  // @@protoc_insertion_point(class_scope:triclass.hardware.Password)
  private static final com.triclass.hardware.Password DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.triclass.hardware.Password();
  }

  public static com.triclass.hardware.Password getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Password>
      PARSER = new com.google.protobuf.AbstractParser<Password>() {
    @java.lang.Override
    public Password parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Password(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Password> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Password> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.triclass.hardware.Password getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

