// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/course_password.proto

package com.triclass.hardware;

public interface PasswordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.hardware.Password)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 主讲人密码
   * </pre>
   *
   * <code>string chairman = 1;</code>
   * @return The chairman.
   */
  java.lang.String getChairman();
  /**
   * <pre>
   * 主讲人密码
   * </pre>
   *
   * <code>string chairman = 1;</code>
   * @return The bytes for chairman.
   */
  com.google.protobuf.ByteString
      getChairmanBytes();

  /**
   * <pre>
   * 参会人密码
   * </pre>
   *
   * <code>string participant = 2;</code>
   * @return The participant.
   */
  java.lang.String getParticipant();
  /**
   * <pre>
   * 参会人密码
   * </pre>
   *
   * <code>string participant = 2;</code>
   * @return The bytes for participant.
   */
  com.google.protobuf.ByteString
      getParticipantBytes();
}
