// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/system.proto

package com.triclass.hardware;

public interface SystemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.hardware.System)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 设置系统状态
   * </pre>
   *
   * <code>.triclass.system.status.SystemStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <pre>
   * 设置系统状态
   * </pre>
   *
   * <code>.triclass.system.status.SystemStatus status = 1;</code>
   * @return The status.
   */
  com.triclass.SystemStatus getStatus();

  public com.triclass.hardware.System.ActionCase getActionCase();
}
