// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/system.proto

package com.triclass.hardware;

public final class SystemOuterClass {
  private SystemOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_triclass_hardware_System_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_triclass_hardware_System_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025hardware/system.proto\022\021triclass.hardwa" +
      "re\032\023system_status.proto\"J\n\006System\0226\n\006sta" +
      "tus\030\001 \001(\0162$.triclass.system.status.Syste" +
      "mStatusH\000B\010\n\006actionB.\n\025com.triclass.hard" +
      "wareP\001Z\023./hardware;hardwareb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.triclass.SystemStatusOuterClass.getDescriptor(),
        });
    internal_static_triclass_hardware_System_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_triclass_hardware_System_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_triclass_hardware_System_descriptor,
        new java.lang.String[] { "Status", "Action", });
    com.triclass.SystemStatusOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
