// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hardware/course_terminate.proto

package com.triclass.hardware;

public interface TerminateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:triclass.hardware.Terminate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 会议编号
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * 会议编号
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
